# program to tell whats the meal time now:

def main():
    time = input("What time is it? ")
    conv_time = convert(time)
    if 7 <= conv_time <= 8:
        print("breakfast time")
    elif 12 <= conv_time <= 13:
        print("lunch time")
    elif 18 <= conv_time <= 19:
        print("dinner time")


def convert(time):
    #pseudo code:
    #Step1:Convert time(str) a into 24hrs format(float)
    #       Eg:like "7:30" (i.e., 7 hours and 30 minutes), convert() should return 7.5 (i.e., 7.5 hours).
    #time1 = float(time.replace(":","."))
    hours, minutes = time.split(":")
    new_mins = int(minutes)/ 60
    # print(new_mins)
    time = float(int(hours)+new_mins)
    # print(time)
    return time

if __name__ == "__main__":
    main()


"""
Results for cs50/problems/2022/python/meal generated by check50 v3.3.7
:) meal.py exists
:( convert successfully returns decimal hours
    expected "7.5", not "7.3\n"
:| input of 7:00 yields output of "breakfast time"
    can't check until a frown turns upside down
:| input of 7:30 yields output of "breakfast time"
    can't check until a frown turns upside down
:| input of 13:00 yields output of "lunch time"
    can't check until a frown turns upside down
:| input of 18:32 yields output of "dinner time"
    can't check until a frown turns upside down
:| input of 11:11 yields no output
    can't check until a frown turns upside down

Results for cs50/problems/2022/python/meal generated by check50 v3.3.7
:) meal.py exists
:( convert successfully returns decimal hours
    expected "14.25", not "14.15\n<class ..."
:| input of 7:00 yields output of "breakfast time"
    can't check until a frown turns upside down
:| input of 7:30 yields output of "breakfast time"
    can't check until a frown turns upside down
:| input of 13:00 yields output of "lunch time"
    can't check until a frown turns upside down
:| input of 18:32 yields output of "dinner time"
    can't check until a frown turns upside down
:| input of 11:11 yields no output
    can't check until a frown turns upside down
    

"""













##################################################################################
# import pdb
# import sample
# print("first line of the code")
# def main():
#     print("inside main")

# def convert():
#     print("inside convert")

# print("before if condition")
# pdb.set_trace()
# if __name__ == "__main__":
#     print("if condition passed, calling main function")
#     main()
#     print("main function called")
# print("outside if")
